name: caller
on:
  workflow_dispatch:
  pull_request:

jobs:
  caller-job-1:
    runs-on: ubuntu-latest
    steps:
    - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
  caller-job-2:
    needs: caller-job-1
    uses: sakula-target/called/.github/workflows/called.yml@main
